import { FC } from "react";

const MorragameInfo: FC = () => {
  return (
    <div className="flex justify-center items-center w-full py-8 mb-8">
      <div className="max-w-full text-center px-4">
        <h2 className="text-2xl font-bold mb-6">Morragame Overview</h2>
        <p className="mb-4">
          Morragame is an interactive guessing game where two "players" (Player 1, the user, and Player 2, the computer) each select a secret number. Player 1 inputs their <strong>choice</strong> and <strong>guess</strong> through the frontend interface, while Player 2's choices are randomly generated by the computer. The goal is for each player to guess the combined sum of both players' choices.
        </p>
        
        <h3 className="text-xl font-bold mt-6">How to Play</h3>
        <ol className="list-decimal pl-8 text-left mx-auto max-w-md mb-6">
          <li className="mb-3">Enter the smart contract's <strong>program ID</strong>.</li>
          <li className="mb-3">
            Choose your number and guess:
            <ul className="list-disc pl-5">
              <li className="mb-2">Enter a number as your <strong>choice</strong>.</li>
              <li className="mb-2">Make a <strong>guess</strong> for the combined sum of both players' choices.</li>
            </ul>
          </li>
          <li className="mb-3">Click the <strong>Compute</strong> button to submit your inputs and compute the results.</li>
        </ol>

        <h3 className="text-xl font-bold mt-6">Understanding the Output</h3>
        <p className="mb-4">
          The game outputs a <code>round_winner</code> with one of the following values:
        </p>
        <ul className="list-disc pl-5 text-left mx-auto max-w-md mb-6">
          <li className="mb-2"><strong>0</strong>: It’s a tie! Neither player guessed the sum correctly.</li>
          <li className="mb-2"><strong>1</strong>: Player 1 (you) won the round by correctly guessing the sum.</li>
          <li className="mb-2"><strong>2</strong>: Player 2 (computer) won the round with a correct guess.</li>
        </ul>
        <p>
          Adjust your guesses in subsequent rounds to try to outsmart the computer!
        </p>
      </div>
    </div>
  );
};

export default MorragameInfo;
